### PR TITLE
[LA.UM.7.1.r1] Add ability to specify a list of devices and/or platforms to build

### PR DESCRIPTION
**Pull request by pablomh**
The following example would allow us to build:
- All the tama devices.
- kugo.
- discovery and pioneer.

PLATFORMS="loire nile tama" LOIRE=kugo NILE="discovery pioneer" ./build-kernels-gcc.sh

### CODE REVIEW

**Comment by jerpelea** [comment]
the kernels will be distributed as prebuit and they are all compiled at the same time this change is not needed

**Comment by MarijnS95** [comment]
In the same way, I guess you won't merge a PR that separates the output directory per device, without removing it for incremental builds @jerpelea?

Keeping in mind that Android 10 does _not_ allow inline building anymore (yes, we can hack around it...) and everyone playing with the kernel needs to run this script now.

**Comment by jerpelea** [comment]
the kernel output separation for each device will just take a lot of space when you build all devices

**Comment by MarijnS95** [comment]
@jerpelea Yes, I see it doesn't work for your case. Do you have a suggestion for generic usage, such as a separate script?

**Comment by pablomh** [comment]
@jerpelea, I agree with @MarijnS95 that this script is very useful now that we can't build inline, so having this functionality in would allow us to keep using this script without impact for your current usage.

**Comment by jerpelea** [comment]
lets talk about it after all devices are booting reliably

**Comment by Thaodan** [comment]
Is there a way to reuse lunch combos and detect which platform and device is used?

**Comment by MarijnS95** [comment]
@Thaodan These are not readily available from the environment (unless we want to parse the name from the output directory or convert the device code (such as `f5121` for Suzu SS), but we can easily ask `get_product_var` for `TARGET_DEVICE` and `SOMC_PLATFORM`.

I'll submit my commits tomorrow (rebased on #6) that take care of this, while still allowing @jerpelea to build clean kernels for all devices.

**Comment by Thaodan** [comment]
Added the same feature to #6 with some small changes.

**Pull request closed without merging**
